# Generated by Django 5.2 on 2025-12-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("DEPOSIT", "예금"), ("SAVING", "적금")], max_length=10
                    ),
                ),
                ("kor_co_nm", models.CharField(max_length=100)),
                ("fin_prdt_nm", models.CharField(max_length=200)),
                ("fin_prdt_cd", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_type", "fin_prdt_cd"),
                        name="unique_producttype_finprdtcd",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.CharField(max_length=50)),
                ("save_trm", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "intr_rate_type_nm",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("intr_rate", models.FloatField(blank=True, null=True)),
                ("intr_rate2", models.FloatField(blank=True, null=True)),
                (
                    "rsrv_type_nm",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.finproduct",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "product",
                            "save_trm",
                            "intr_rate",
                            "intr_rate2",
                            "rsrv_type_nm",
                        ),
                        name="unique_option_per_product",
                    )
                ],
            },
        ),
    ]
